# Generated by Django 3.2.3 on 2021-05-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebull', '0002_alter_user_ip_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
    ]
