# Generated by Django 3.2.3 on 2021-05-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebull', '0003_user_holiday'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
